"""Resolve missing NSE price identities from the existing company master.

Native ISINs remain authoritative. Never infer BSE identities from NSE symbols.
Ambiguous master symbols remain unresolved and are reported, never last-row-wins.
"""
import logging
import os
import re

logger = logging.getLogger(__name__)
ISIN = re.compile(r'^[A-Z]{2}[A-Z0-9]{9}[0-9]$')


def identity_map(rows):
    choices = {}
    for symbol, isin in rows:
        symbol = str(symbol or '').strip().upper()
        isin = str(isin or '').strip().upper()
        if symbol and ISIN.fullmatch(isin):
            choices.setdefault(symbol, set()).add(isin)
    ambiguous = sorted(s for s, values in choices.items() if len(values) > 1)
    if ambiguous:
        logger.warning('Ambiguous NSE symbols excluded from identity enrichment: %s', ambiguous)
    return sorted((s, next(iter(values))) for s, values in choices.items() if len(values) == 1)


def load_identity_rows():
    import psycopg2
    conn = psycopg2.connect(os.environ['CC_POSTGRES_URL'], connect_timeout=15,
                           options='-c statement_timeout=15000')
    try:
        conn.set_session(readonly=True)
        with conn.cursor() as cur:
            cur.execute('SELECT nse_symbol, isin FROM investmitra.company_master '
                        'WHERE nse_symbol IS NOT NULL AND isin IS NOT NULL')
            return cur.fetchall()
    finally:
        conn.close()


def prepare_price_inputs(con, path, start, target, rows=None):
    """Read the bounded lake history once; retain input and mapping diagnostics."""
    import pandas as pd
    mappings = identity_map(load_identity_rows() if rows is None else rows)
    if not mappings:
        raise RuntimeError('NSE identity mapping unavailable; feature build blocked')
    frame = pd.DataFrame(mappings, columns=['nse_symbol', 'mapped_isin'])
    con.register('nse_identity_map', frame)
    # Path is generated by build_path (SQL string/list literal), not user SQL.
    con.execute(f'CREATE TEMP VIEW feature_lake AS SELECT * FROM read_parquet({path}, '
                'union_by_name=true, hive_partitioning=true)')
    columns = {r[0] for r in con.execute('DESCRIBE feature_lake').fetchall()}
    symbol = 'UPPER(TRIM(CAST(p.nse_symbol AS VARCHAR)))' if 'nse_symbol' in columns else 'NULL::VARCHAR'
    con.execute(f'''CREATE TEMP TABLE feature_inputs AS
        SELECT COALESCE(NULLIF(TRIM(CAST(p.isin AS VARCHAR)),''),
                       CASE WHEN UPPER(TRIM(p.source))='NSE' THEN m.mapped_isin END) AS isin,
               UPPER(TRIM(p.source)) AS source, p.trade_date::DATE AS trade_date,
               p.close::DOUBLE AS close, p.volume::BIGINT AS volume,
               p.turnover_cr::DOUBLE AS turnover_cr, p.delivery_pct::DOUBLE AS delivery_pct,
               {symbol} AS nse_symbol,
               (NULLIF(TRIM(CAST(p.isin AS VARCHAR)),'') IS NULL AND m.mapped_isin IS NOT NULL
                AND UPPER(TRIM(p.source))='NSE') AS identity_enriched
        FROM feature_lake p LEFT JOIN nse_identity_map m ON {symbol}=m.nse_symbol
        WHERE p.trade_date::DATE BETWEEN ? AND ? AND p.close IS NOT NULL AND p.close > 0''',
        [start, target])
    stats = con.execute('''SELECT COUNT(*), COUNT(*) FILTER(WHERE identity_enriched),
        COUNT(*) FILTER(WHERE source='NSE' AND trade_date=? AND isin IS NULL)
        FROM feature_inputs''', [target]).fetchone()
    logger.info('Price identities: input_rows=%d enriched_nse_rows=%d unresolved_target_nse_rows=%d', *stats)
    if stats[2]:
        unknown = con.execute('''SELECT DISTINCT nse_symbol FROM feature_inputs
            WHERE source='NSE' AND trade_date=? AND isin IS NULL ORDER BY nse_symbol LIMIT 20''', [target]).fetchall()
        logger.warning('Unresolved target NSE symbols (first 20): %s', [r[0] for r in unknown])
    con.unregister('nse_identity_map')
